version: '3.9'

services:
  frontend:
    build: ./apps/frontend
    networks:
      - internal
      - reverse_proxy
    expose:
      - "80"
    restart: unless-stopped
    container_name: frontend
  
  rest_api:
    build: ./apps/rest-api
    depends_on:
      - postgres
      - mongo
    networks:
      - internal
    restart: unless-stopped
    container_name: rest-api
  
  ws_api:
    build: ./apps/ws-api
    networks:
      - internal
    restart: unless-stopped
    container_name: ws-api
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - internal
    restart: unless-stopped
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - rest_api
      - ws_api
    networks:
      - reverse_proxy
      - internal
    restart: unless-stopped
    container_name: nginx
  
volumes:
  postgres_data:
  mongo_data:

networks:
  internal:
    internal: true
  reverse_proxy:
    driver: bridge