name: Release Android App APK

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/android-app/**'
      - '.github/workflows/release-android.yml'


jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
      
      - name: Install dependencies
        working-directory: apps/android-app
        run: flutter pub get
      
      - name: Build APK
        working-directory: apps/android-app
        run: flutter build apk --release --dart-define=BASE_URL=${{ secrets.BASE_URL }}

      - name: Clean release folder
        run: |
          rm -rf apps/android-app/release/*
      
      - name: Copy APK to release folder
        run: |
          cp apps/android-app/build/app/outputs/flutter-apk/app-release.apk apps/android-app/release/