name: Lint and Validate Configs

on:
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/docker-compose.yml'
      - '**/nginx.conf'
      - '.github/workflows/*.yml'
  workflow_dispatch:


jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install hadolint
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/
      
      - name: Lint Dockerfiles
        run: |
          find . -name Dockerfile -exec hadolint {} \;


  validate-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate docker-compose.yml
        run: docker compose config -q

  validate-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Prepare and validate nginx.conf
        run: |
          CONFIG_PATH=nginx/nginx.conf

          mkdir -p dummy_ssl/etc/ssl dummy_ssl/etc/ssl/private

          cat > dummy_ssl/etc/ssl/cloudflare.crt <<EOF
          -----BEGIN CERTIFICATE-----
          MIIBjzCCATSgAwIBAgIUe1LKdD8RhJLPWbZ38cO/ypO7JfkwCgYIKoZIzj0EAwIw
          EjEQMA4GA1UEAwwHZXhhbXBsZTAeFw0yMDAxMDEwMDAwMDBaFw0zMDAxMDEwMDAw
          MDBaMBIxEDAOBgNVBAMMB2V4YW1wbGUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
          AAQqPMB71ReD4ko6SIVr9uEry7E9uGqSp3J4mPklXeou7lsdlGyo7fBSkJ5u/0vV
          h5k9YzWv0SE2HtQ3GZ7hyZTxo1MwUTAdBgNVHQ4EFgQUVQzNY9cNYJcQnXnyocV3
          vM3DiPyAwHwYDVR0jBBgwFoAUVQzNY9cNYJcQnXnyocV3vM3DiPyAwDwYDVR0TAQ
          H/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBEAiA+LtEz6K0zQjDtBz+K/MoCFql0fY
          XrNg0Ijw+uDb0vzmSAIgCw4k6sWc1mFY8d2DYiLaPzHcCUiLFG6v0kpMCh/4Sv1w
          -----END CERTIFICATE-----
          EOF

          cat > dummy_ssl/etc/ssl/private/cloudflare.key <<EOF
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIO3MGzmkb8pAP9Ju1mQzI8jw8Y83ysI1wdtHkpHOqWpYooAoGCCqGSM49
          AwEHoUQDQgAEKjzwe9UXg+JKOiIla/bgK8uxPbhqkqdyeJj5JV3qLu5bHZRsqO3w
          UpCebv9L1YeZPWM1r9EhNh7UNxm
          -----END EC PRIVATE KEY-----
          EOF

          #NOT ACTUAL KEYS. SAFE FOR PUBLICITY

          sed -e 's|/etc/ssl/cloudflare.crt|'"$(pwd)"'/dummy_ssl/etc/ssl/cloudflare.crt|g' \
              -e 's|/etc/ssl/private/cloudflare.key|'"$(pwd)"'/dummy_ssl/etc/ssl/private/cloudflare.key|g' \
              -e 's/frontend:80/127.0.0.1:8080/g' \
              -e 's/rest-api:80/127.0.0.1:8081/g' \
              -e 's/ws-api:80/127.0.0.1:8082/g' \
              $CONFIG_PATH > temp.conf

          nginx -t -c $(pwd)/temp.conf


  validate-workflows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate GitHub Actions workflows
      run: |
        docker run --rm -v ${{ github.workspace }}:/mnt rhysd/actionlint sh -c "find /mnt/.github/workflows -type f \\( -name '*.yml' -o -name '*.yaml' \\) -exec actionlint {} +"

